### ISSUE TITLE
Q4 changes

### ISSUE THREAD

**Issue by kkarimovahashkes** [USAID-OHA-SI/q4_or_bust#10]
Are there any expected changes in Q4 data you are aware of that can result in Prep flow modification and therefore Python code changes?

**Comment by achafetz** [comment]
No, process changes for the Prep flow envisioned at this time.

**Comment by nmcdavid** [comment]
None that i'm aware of. This might change if the underlying MSD structure or data is changed (based on DATIM Release Notes) at Q4 release. If that is the case I'll let you know ASAP
