### ISSUE TITLE
TX_VL_COVERAGE calculation

### ISSUE THREAD

**Issue by kkarimovahashkes** [USAID-OHA-SI/q4_or_bust#12]
I read your comments re the above calculation in the pseudocode, and if I follow the flow steps exactly I get the same outputs as in flow. However, I don't understand it well enough to refactor. Could you please explain the meaning behind the flow steps and how TX_VL_COVERAGE should be calculated if not using the Tableau Prep?
We can discuss it during a call if it's easier. Thanks!

**Comment by nmcdavid** [comment]
@kkarimovahashkes - as noted in the issue #2 , the VL coverage calculation is as follows
